// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgvstHsAbZjsOMQb6FrBZ5ZgSnOg_y9Q',
    appId: '1:958104916805:ios:9595c97fb98e89b357a42c',
    messagingSenderId: '958104916805',
    projectId: 'lacarta-1a',
    storageBucket: 'lacarta-1a.firebasestorage.app',
    iosBundleId: 'com.example.lacarta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtgvstHsAbZjsOMQb6FrBZ5ZgSnOg_y9Q',
    appId: '1:958104916805:ios:9595c97fb98e89b357a42c',
    messagingSenderId: '958104916805',
    projectId: 'lacarta-1a',
    storageBucket: 'lacarta-1a.firebasestorage.app',
    iosBundleId: 'com.example.lacarta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2YwMQvIXcTMMnnIM8XzCYG48Jte_4C7Q',
    appId: '1:958104916805:web:ce884b15c27a619c57a42c',
    messagingSenderId: '958104916805',
    projectId: 'lacarta-1a',
    authDomain: 'lacarta-1a.firebaseapp.com',
    storageBucket: 'lacarta-1a.firebasestorage.app',
    measurementId: 'G-2YC2CMTT73',
  );

}